version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - KEYCLOAK_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myclient
      - KEYCLOAK_SECRET=mysecret
    depends_on:
      - mariadb
      - keycloak

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    deploy:
      replicas: 1

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/keycloak_config.json:/opt/jboss/keycloak/standalone/configuration/keycloak_config.json
